config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  root to: 'pages#home'
  resources :users
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  
  validates :name, presence: true, length: { maximum: 20 }
  validates :deadline, presence: true
  validate :date_before_start


  def date_before_start
    errors.add(:deadline, "は今日以降のものを選択してください") if deadline.nil? || deadline < Date.today
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },format: { with: VALID_EMAIL_REGEX },uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user
  
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  
  def autheniticate_user
    if @current_user == nil
      flash[:success] = "ログインが必要です"
      redirect_to login_path
    end
  end
  
  def is_login?
    if @current_user 
      flash[:success] = "すでにログインしています"
      redirect_to products_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :autheniticate_user, {only:[:new, :create, :edit, :update, :destroy]}
  #ログインしているのかを確かめる
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  def index
    @products = current_user.products.all
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = current_user.products.new(product_params)
    if @product.save
      flash[:success] = "「#{@product.name}」を登録しました。"
      redirect_to products_path
    else
      render :new
    end
  end
  
  
  def show
  end

  def edit
  end
  
  def update
    if @product.update(product_params)
      flash[:success] = "#{@product.name}を更新しました。"
      redirect_to products_path
    else
      render :edit
    end
  end
  
  def destroy
    @product.destroy!
    redirect_to products_path
  end
  private
  
  def product_params
    params.require(:product).permit(:name, :deadline)
  end
  
  
  def set_product
    @product = current_user.products.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :is_login?, {only: [:new, :create]}
  #ログイン中のユーザーはログイン画面にアクセスできない
  def new
  end
  def create
    user = User.find_by(email: session_params[:email])
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      flash[:success] = "ログインしました"
      redirect_to user
    else
      flash.now[:danger] = 'メールアドレスとパスワードの組み合わせが誤っています'
      render :new
    end
  end
  
  def destroy
    reset_session
    flash[:success] = "ログアウトしました"
    redirect_to root_path
  end
  
  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :autheniticate_user,{only:[:index,:show,:edit,:update]}
  #ログインしているのかを確かめる
  before_action :ensure_correct_user, {only: [:show, :edit, :update]}
  #ユーザーの編集ができるのはそのユーザー自身だけにする
  before_action :is_login?, {only: [:new, :create]}
  #ログイン中のユーザーは新規登録画面にアクセスできない
  before_action :set_user, {only: [:show, :edit, :update]}
  # 共通部分
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      #新規登録をしたそのままログイン状態にする
      flash[:success] = "ようこそ！#{@user.name}さん"
      redirect_to products_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "プロフィールを更新しました"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end
  
  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:success] = "権限がありません"
      redirect_to products_path
    end
  end
  
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_google_analytics.html.erb
<script async src="https://www.googletagmanager.com/gtag/js?id=G-Z9JZ9YHS2G"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-Z9JZ9YHS2G');
  if (#{raw current_user.to_json}) {
    gtag('set', {'user_id': #{raw current_user.to_json}.id});
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductApp</title>
    <%= analytics_init if Rails.env.production? %>
    <%= render 'shared/rails_default' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
            <html>
            <head>
  
  </head>
<section class="fdb-block">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-10 col-sm-6 col-md-5 col-lg-4 m-auto pb-5 pb-md-0">
        <img alt="image" class="img-fluid rounded-0" src="/images/ipad-hand.png">
      </div>

      <div class="col-12 ml-md-auto col-md-7 col-lg-6 pb-5 pb-md-0">
        <h1>食材の賞味期限を管理</h1>
        <p class="lead">あれもこれも賞味期限間近。一人暮らしあるある「余る問題」を解消する</p>
        <p class="mt-4">
          <%= link_to 'はじめる', new_user_path, class:"btn btn-secondary" %>
        </p>
      </div>
    </div>
  </div>
</section>
<section class="fdb-block">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 text-left">
        <h1>使い方</h1>
      </div>
    </div>

    <div class="row text-left mt-5">
      <div class="col-12 col-sm-8 col-md-4 col-lg-3 m-sm-auto mr-md-auto ml-md-0">
        <img alt="image" class="img-fluid rounded" src="/images/product-new1.png">
        <h3><strong>ステップ1</strong></h3>
        <p>ログインして商品一覧画面に行き、新商品登録をクリック</p>
      </div>

      <div class="col-12 col-sm-8 col-md-4 col-lg-3 m-sm-auto pt-5 pt-md-0">
        <img alt="image" class="img-fluid rounded" src="/images/product-new2.png" size="500*800">
        <h3><strong>ステップ2</strong></h3>
        <p>商品名を賞味期限を入力する<br>(商品名は日本語で入力してください)</p>
      </div>

      <div class="col-12 col-sm-8 col-md-4 col-lg-3 m-sm-auto ml-md-auto mr-md-0 pt-5 pt-md-0">
        <img alt="image" class="img-fluid rounded" src="/images/recipe-mail.png" size="500*800">
        <h3><strong>ステップ3</strong></h3>
        <p>賞味期限の3日前になるとメールが届く。その材料を使ったオススメのレシピが載っている。</p>
      </div>
    </div>
  </div>
</section>
<section class="fdb-block py-0">
  <div class="container py-5 my-5" style="background-image: url(imgs/shapes/9.svg);" size="500*800">
    <div class="row py-5">
      <div class="col py-5">
        <div class="fdb-box fdb-touch">
          <div class="row text-center justify-content-center">
            <div class="col-12 col-md-9 col-lg-7">
              <h1>お問い合わせフォーム</h1>
              <p class="lead">下記フォーマットにご記入いただき内容をご確認のうえ、送信してください。</p>
            </div>
          </div>

          <div class="row justify-content-center pt-4">
            <div class="col-12 col-md-8">
              <form>
                <div class="row">
                  <div class="col-12 col-md">
                    <input type="text" class="form-control" placeholder="名前">
                  </div>
                  <div class="col-12 col-md mt-4 mt-md-0">
                    <input type="text" class="form-control" placeholder="メールアドレス">
                  </div>
                </div>

                <div class="row mt-4">
                  <div class="col">
                    <input type="email" class="form-control" placeholder="件名">
                  </div>
                </div>

                <div class="row mt-4">
                  <div class="col">
                    <textarea class="form-control" name="message" rows="3" placeholder="お問い合わせ内容"></textarea>
                  </div>
                </div>
                <div class="row mt-4">
                  <div class="col text-center">
                    <button type="submit" class="btn btn-primary">送信</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/products/edit.html.erb
<section class="fdb-block">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-8 col-lg-7 col-md-5 text-center">
        <div class="fdb-box fdb-touch">
          <div class="row">
            <div class="col">
              <h1>商品編集</h1>
            </div>
          </div>
          <%= form_with model: @product, local: true do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <div class="row">
              <div class="col mt-4">
                <%= f.text_field :name, class: 'form-control', placeholder: "Product Name"%>
              </div>
            </div>
            <div class="row mt-4">
              <div class="col">
                <%= f.date_field :deadline, class: 'form-control', placeholder: "Date" %>
              </div>
            </div>
            <div class="row mt-4">
              <div class="col">
                <%= f.submit nil, class: 'btn btn-primary' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/products/index.html.erb
<%= render 'shared/flash_messages' %>
<section class="fdb-block">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-sm-8 col-md-6 col-lg-6 text-center">
        <h2>
          <strong>商品一覧</strong>
        </h2>
        <p class="mt-5 mt-sm-4">
          <%= link_to '新商品登録', new_product_path, class: 'btn btn-outline-primary' %>
        </p>
      </div>
    </div>
  </div>
</section>
<div class="container">
  <div class="row">
    <div class="col-12">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">商品名</th>
            <th scope="col">期限</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
           <% @products.each do |product| %>
              <tr>
                <td><%= product.name %></td>
                <td><%= product.deadline %></td>
                <td>
                    <%= link_to  edit_product_path(product), class: 'btn btn-success' do %>
                      <i class="fas fa-edit"></i>
                    <% end %>
                    <%= link_to product, method: :delete, remote: true, data: { confirm: "「#{product.name}」を削除をします。よろしいですか？"}, class: 'btn btn-danger delete' do %>
                      <i class="far fa-trash-alt"></i>
                    <% end %>
                </td>
              </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<section class="fdb-block">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-8 col-lg-7 col-md-5 text-center">
        <div class="fdb-box fdb-touch">
          <div class="row">
            <div class="col">
              <h1>商品登録</h1>
            </div>
          </div>
          <%= form_with model: @product, local: true do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <div class="row">
              <div class="col mt-4">
                <%= f.text_field :name, class: 'form-control', placeholder: "商品名"%>
              </div>
            </div>
            <div class="row mt-4">
              <div class="col">
                <%= f.date_field :deadline, class: 'form-control', placeholder: "賞味期限" %>
              </div>
            </div>
            <div class="row mt-4">
              <div class="col">
                <%= f.submit nil, class: 'btn btn-primary' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
      <% object.errors.full_messages.each do |message| %>
        <%= message %><br>
      <% end %>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="fdb-block footer-small">
  <div class="container">
    <div class="row text-center">
      <div class="col">
        <p>© 2018 Froala. All Rights Reserved</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="container">
    <nav class="navbar navbar-expand-md">
      <%= link_to root_path, class:"navbar-brand" do %>
        <%= image_tag "/images/twitter_header_photo_1.png", height:"40", alt:"image", width:"250" %>
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav3" aria-controls="navbarNav3" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav3">
        <ul class="navbar-nav ml-auto">
          <% if @current_user.present? %>
            <li class="nav-item active">
              <%= link_to 'HOME', root_path , class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to '商品', products_path , class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'プロフィール', @current_user , class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'ログアウト', logout_path, method: :delete, class:"btn btn-outline-primary ml-md-3"%>
            </li>
          <% else %>
            <li class="nav-item active">
              <%= link_to 'HOME', root_path , class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'サインイン', new_user_path, class:"btn btn-outline-primary ml-md-3"%>
            </li>
            <li class="nav-item">
              <%= link_to 'ログイン', login_path, class:"btn btn-outline-primary ml-md-3"%>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/users/edit.html.erb
<section class="fdb-block py-0">
  <div class="container bg-r py-5 my-5" style="background-image: url(/images/2.svg);">
    <div class="row py-5">
      <div class="col-12 col-sm-10 col-md-8 col-lg-6 text-left">
        <h1>プロフィール</h1>
        <%= form_with model: @user, local: true  do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
            <div class="row mt-4">
              <div class="col">
                <%= f.text_field :name, class:"form-control", placeholder:"Name" %>
              </div>
            </div>
            <div class="row mt-4">
              <div class="col">
                <%= f.email_field :email, class:"form-control", placeholder:"Email" %>
              </div>
            </div>
            <div class="row mt-4">
              <div class="col">
                <%= f.password_field :password, class:"form-control", placeholder:"Password" %>
              </div>
            </div>
            <div class="row mt-4">
              <div class="col">
                <%= f.password_field :password_confirmation, class:"form-control mb-1", placeholder:"Password（確認用）" %>
              </div>
            </div>
            <div class="row mt-4">
              <div class="col">
                <%= f.submit nil, class: 'btn btn-outline-dark' %>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/new.html.erb
<section class="fdb-block" style="background-image: url(/images/blue.svg);">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-8 col-lg-7 col-xl-5 text-center">
        <div class="fdb-box">
          <div class="row">
            <div class="col">
              <h1>サインイン</h1>
            </div>
          </div>
          <%= form_with model: @user, local: true  do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <div class="row mt-4">
              <div class="col">
                <%= f.text_field :name, class:"form-control", placeholder:"name" %>
              </div>
            </div>
            <div class="row mt-4">
              <div class="col">
                <%= f.email_field :email, class:"form-control", placeholder:"Email" %>
              </div>
            </div>
            <div class="row mt-4">
              <div class="col">
                <%= f.password_field :password, class:"form-control", placeholder:"Password" %>
              </div>
            </div>
            <div class="row mt-4">
              <div class="col">
                <%= f.password_field :password_confirmation, class:"form-control mb-1", placeholder:"Password（確認用）" %>
              </div>
            </div>
            <div class="row mt-4">
              <div class="col">
                <%= f.submit nil, class: 'btn btn-outline-secondary' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="fdb-block py-0">
  <%= render 'shared/flash_messages' %>
  <div class="container bg-r py-5 my-5" style="background-image: url(/images/1.svg);">
    <div class="row py-5">
      <div class="col-12 col-sm-10 col-md-8 col-lg-6 text-left">
        <h1>プロフィール</h1>
        <p class="lead">
          ユーザー名<%= @user.name %><br>
          <%= @user.email %>
        </p>
        <% if @current_user.id == @user.id %>
          <p class="mt-4">
            <%= link_to '編集', edit_user_path, class:"btn btn-primary"%>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</section>